var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //counties outline
	},
	'map_1':{
		'hover': 'ALAMEDA',//county hover content
		'enable':true,//true/false to enable/disable this county
		'url':'http://www.beacondataresearch.com/interactivemap/', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#eff9ff', //county color when page loads
		'overColor':'#ffcc5f', //county color when mouse hover
		'downColor':'#477cb2',//county color when mouse clicking
	},
	'map_2':{	
		'hover': '<u><b>ALPINE</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_3':{
		'hover': 'AMADOR</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_4':{
		'hover': 'BUTTE</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_5':{
		'hover': 'CALAVERAS<</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_6':{
		'hover': 'COLUSA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_7':{
		'hover': 'CONTRA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_8':{
		'hover': 'DEL NORTE</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_9':{
		'hover': 'EL DORADO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_10':{
		'hover': '<u><b>FRESNO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_11':{
		'hover': 'GLENN</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_12':{
		'hover': '<u><b>HUMBOLDT</b></u><br><span style="color: #bcbcbc;">LINE 1</span><br>&nbsp;LINE 2<br><span style="color: #bcbcbc;">LINE 3</span><br>&nbsp;LINE 4<br>&nbsp;LINE 5<br>&nbsp;LINE 6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_13':{
		'hover': 'IMPERIAL</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_14':{
		'hover': 'INYO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_15':{
		'hover': '<u><b>KERN</b></u><br><span style="color: #bcbcbc;">LINE 1</span><br>&nbsp;LINE 2<br><span style="color: #bcbcbc;">LINE 3</span><br>&nbsp;LINE 4<br>&nbsp;LINE 5<br>&nbsp;LINE 6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_16':{
		'hover': 'KINGS</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_17':{
		'hover': 'LAKE</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_18':{
		'hover': 'LASSEN</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_19':{
		'hover': '<u><b>LOS ANGELES</b></u><br><span style="color: #bcbcbc;">LINE 1</span><br>&nbsp;LINE 2<br><span style="color: #bcbcbc;">LINE 3</span><br>&nbsp;LINE 4<br>&nbsp;LINE 5<br>&nbsp;LINE 6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_20':{
		'hover': 'MADERA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_21':{
		'hover': 'MARIN</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_22':{
		'hover': 'MARIPOSA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_23':{
		'hover': 'MENDOCINO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_24':{
		'hover': 'MERCED</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_25':{
		'hover': 'MODOC</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_26':{
		'hover': 'MONO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_27':{
		'hover': '<u><b>MONTEREY</b></u><br><span style="color: #bcbcbc;">LINE 1</span><br>&nbsp;LINE 2<br><span style="color: #bcbcbc;">LINE 3</span><br>&nbsp;LINE 4<br>&nbsp;LINE 5<br>&nbsp;LINE 6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_28':{
		'hover': 'NAPA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_29':{
		'hover': 'NEVADA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_30':{
		'hover': '<u><b>ORANGE</b></u><br><span style="color: #bcbcbc;">LINE 1</span><br>&nbsp;LINE 2<br><span style="color: #bcbcbc;">LINE 3</span><br>&nbsp;LINE 4<br>&nbsp;LINE 5<br>&nbsp;LINE 6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_31':{
		'hover': 'PLACER</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_32':{
		'hover': 'PLUMAS</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_33':{
		'hover': 'RIVERSIDE</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_34':{
		'hover': 'SACRAMENTO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_35':{
		'hover': 'SAN BENITO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_36':{
		'hover': '<u><b>SAN BERNARDINO</b></u><br><span style="color: #bcbcbc;">Cultivators</span><br>&nbsp;5<br><span style="color: #bcbcbc;">Manufacturers/Dispensaries</span><br>&nbsp;Mfg-3<br>&nbsp;Disp-6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_37':{
		'hover': '<u><b>SAN DIEGO</b></u><br><span style="color: #bcbcbc;">LINE 1</span><br>&nbsp;LINE 2<br><span style="color: #bcbcbc;">LINE 3</span><br>&nbsp;LINE 4<br>&nbsp;LINE 5<br>&nbsp;LINE 6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_38':{
		'hover': 'SAN FRANCISCO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_39':{
		'hover': 'SAN JOAQUIN</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_40':{
		'hover': '<u><b>SAN LUIS OBISPO</b></u><br><span style="color: #bcbcbc;">LINE 1</span><br>&nbsp;LINE 2<br><span style="color: #bcbcbc;">LINE 3</span><br>&nbsp;LINE 4<br>&nbsp;LINE 5<br>&nbsp;LINE 6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_41':{
		'hover': 'SAN MATEO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_42':{
		'hover': 'SANTA BARBARA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_43':{
		'hover': 'SANTA CLARA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_44':{
		'hover': 'SANTA CRUZ</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_45':{
		'hover': 'SHASTA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_46':{
		'hover': 'SIERRA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_47':{
		'hover': 'SISKIYOU</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_48':{
		'hover': 'SOLANO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_49':{
		'hover': 'SONOMA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_50':{
		'hover': 'STANISLAUS</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_51':{
		'hover': 'SUTTER</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_52':{
		'hover': 'TEHAMA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_53':{
		'hover': '<u><b>TRINITY</b></u><br><span style="color: #bcbcbc;">LINE 1</span><br>&nbsp;LINE 2<br><span style="color: #bcbcbc;">LINE 3</span><br>&nbsp;LINE 4<br>&nbsp;LINE 5<br>&nbsp;LINE 6',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#B9D3EE',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_54':{
		'hover': 'TULARE</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_55':{
		'hover': 'TUOLUMNE</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_56':{
		'hover': 'VENTURA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_57':{
		'hover': 'YOLO</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
	'map_58':{
		'hover': 'YUBA</b></u><br><span style="color:white;">data unavailable</span>',
		'enable':true,
		'url':'http://www.beacondataresearch.com/interactivemap/',
		'target':'same_window',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
	},
}
